# Generated by Django 5.0.7 on 2024-07-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='course/course/')),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('active_students', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='course/teacher/')),
                ('social_link_telegram', models.URLField()),
                ('social_link_linkedin', models.URLField()),
                ('social_link_youtobe', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(upload_to='course/speciality/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.teacher'),
        ),
    ]
