# Generated by Django 5.0.7 on 2024-07-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='social_link_linkedin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='social_link_telegram',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='social_link_youtobe',
        ),
    ]
